#pragma once
#include <Windows.h>

class ColorPalette {
public:
	WORD standard = FOREGROUND_GREEN;
	WORD logo = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD press_start = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD player_amount = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD player_1 = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
	WORD player_2 = FOREGROUND_RED | FOREGROUND_INTENSITY;
	WORD fruit = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD fruit_swallowed = FOREGROUND_RED | FOREGROUND_BLUE;
	WORD portal = FOREGROUND_BLUE;
	WORD keyboard = FOREGROUND_GREEN;
	WORD keyboard_selected = BACKGROUND_GREEN;
	WORD hud = FOREGROUND_GREEN;


	WORD bright_cyan = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD green = FOREGROUND_GREEN;
	WORD bright_green = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
	WORD red = FOREGROUND_RED;
	WORD bright_red = FOREGROUND_RED | FOREGROUND_INTENSITY;
	WORD pink = FOREGROUND_RED | FOREGROUND_BLUE;
	WORD bright_pink = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD white = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
	WORD grey = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
	WORD black = 0;
};

